name: build using github actions

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        image:
          - name: avatar.api
            dockerfile: ./deploy/api.dockerfile
            tag: latest
          - name: avatar.web
            dockerfile: ./deploy/web.dockerfile
            tag: latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}/${{ matrix.image.name }}:${{ matrix.image.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          ## if you want to use a personal access token
          ## to authenticate against another private repository
          ## use a secret named GIT_AUTH_TOKEN
          ##secrets: |
            ##GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}