name: scout analyze image

on:
  push:

env:
  REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./deploy/api.dockerfile
            image_name: avatar_api
            image_tag: latest
          - dockerfile: ./deploy/web.dockerfile
            image_name: avatar_web
            image_tag: latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          ##tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository.name }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
          
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}

          labels: ${{ steps.meta.outputs.labels }}
          ## if you want to use a personal access token
          ## to authenticate against another private repository
          ## use a secret named GIT_AUTH_TOKEN
          ##secrets: |
            ##GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
      - name: Analyze image for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          ##image: ${{ steps.meta.outputs.tags }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
          sarif-file: sarif.output.json
          summary: true
      - name: Upload CVEs (SARIF) result
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json