name: build using github actions

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./deploy/api.dockerfile
            image: ghcr.io/username/avatar.api
          - dockerfile: ./deploy/web.dockerfile
            image: ghcr.io/username/avatar.web
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          ## if you want to use a personal access token
          ## to authenticate against another private repository
          ## use a secret named GIT_AUTH_TOKEN
          ##secrets: |
            ##GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}