name: Scout - image cves

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./deploy/api.dockerfile
            image_name: avatars_api
            image_tag: latest
          - dockerfile: ./deploy/web.dockerfile
            image_name: avatars_web
            image_tag: latest
    steps:
      # # Checkout code
      # - name: Checkout code
      #   uses: actions/checkout@v3
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # # Setup QEMU
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # # Setup Docker Buildx
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # # Extract metadata (tags, labels) for Docker
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}
      # # Build and push
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ${{ matrix.dockerfile }}
      #     push: false
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
      #     labels: ${{ steps.meta.outputs.labels }}
      # Analyze image for critical and high CVEs
      - name: Analyze image for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
          sarif-file: sarif.output.json
          summary: true
      # - name: Upload CVEs (SARIF) result
      #   id: upload-sarif
      #   if: ${{ github.event_name != 'pull_request_target' }}
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: sarif.output.json