name: build using github actions

on:
  push:

env:
  REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./deploy/api.dockerfile
            image_name: avatar_api
            image_tag: latest
          - dockerfile: ./deploy/web.dockerfile
            image_name: avatar_web
            image_tag: latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "demonstrationorg/default"
          install: true
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          ##tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository.name }}/${{ matrix.image_name }}:${{ matrix.image_tag }}
          
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ matrix.image_tag }}

          labels: ${{ steps.meta.outputs.labels }}
          ## if you want to use a personal access token
          ## to authenticate against another private repository
          ## use a secret named GIT_AUTH_TOKEN
          ##secrets: |
            ##GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}